FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build

WORKDIR /app

COPY . .

RUN dotnet restore
RUN dotnet build

WORKDIR /app

ENTRYPOINT dotnet run --project "Test Harness/App/testharness.app.csproj"